server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://47.106.248.229:3306/consumer?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true
    username: jgm
    password: 0000
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      maxActive: 100
      maxIdle: 20
      minIdle: 10
      initialSize: 10
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      removeAbandoned: true
      logAbandoned: true
      validationQuery: SELECT 1
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 30000
      validationInterval: 30000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.beiming.consumer.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  enumAsSimpleType: true
#dubbo:
##  application:
##    name: consumer
#  registry:
#    protocol: zookeeper
#    address: 47.106.248.229:2181
#  protocol:
#    name: dubbo
#    port: 23870


rocketmq:
  name-server: 47.106.248.229:9876
  producer:
    group: smsProducerGroup
  consumer:
    group: smsConsumerGroup
  topic: smsTopic


#dubbo:
#  appName: dubbo-annotation-consumer


Platform: provider



