server:
  port: 8082

dubbo:
  application:
    name: demo_service
  registry:
    protocol: zookeeper
    address: 47.106.248.229:2181
  protocol:
    name: dubbo
    port: 23871
rocketmq:
  name-server: 47.106.248.229:9876
  producer:
    group: smsProducerGroup
  consumer:
    group: smsConsumerGroup
  topic: smsTopic



