server:
  port: 8084


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.beiming.provider.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  enumAsSimpleType: true
#dubbo:
#  application:
#    name: provider
#  registry:
#    protocol: zookeeper
#    address: 47.106.248.229:2181
#  protocol:
#    name: dubbo
#    port: 23871
rocketmq:
  name-server: 47.106.248.229:9876
  producer:
    group: smsProducerGroup
  consumer:
    group: smsConsumerGroup
  topic: smsTopic


Platform: consumer


